lib/react_workshop_feedback_web/router.ex
defmodule ReactWorkshopFeedbackWeb.Router do
  use ReactWorkshopFeedbackWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ReactWorkshopFeedbackWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/feedbacks", FeedbackController
    resources "/volunteers", VolunteerController
  end

  # Other scopes may use custom stacks.
  # scope "/api", ReactWorkshopFeedbackWeb do
  #   pipe_through :api
  # end
end

lib/react_workshop_feedback/studentcomment/feedback.ex
defmodule ReactWorkshopFeedback.Studentcomment.Feedback do
  use Ecto.Schema
  import Ecto.Changeset

  schema "feedbacks" do
    field :food_feedback, :string
    field :improvement, :string
    field :next_session, :string
    field :session1_feedback, :string
    field :session2_feedback, :string

    timestamps()
  end

  @doc false
  def changeset(feedback, attrs) do
    feedback
    |> cast(attrs, [:session1_feedback, :session2_feedback, :food_feedback, :improvement, :next_session])
    |> validate_required([:session1_feedback, :session2_feedback, :food_feedback, :improvement, :next_session])
  end
end

lib/react_workshop_feedback_web/controllers/feedback_controller.ex
defmodule ReactWorkshopFeedbackWeb.FeedbackController do
  use ReactWorkshopFeedbackWeb, :controller

  alias ReactWorkshopFeedback.Studentcomment
  alias ReactWorkshopFeedback.Studentcomment.Feedback

  def index(conn, _params) do
    feedbacks = Studentcomment.list_feedbacks()
    render(conn, "index.html", feedbacks: feedbacks)
  end

  def new(conn, _params) do
    changeset = Studentcomment.change_feedback(%Feedback{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"feedback" => feedback_params}) do
    case Studentcomment.create_feedback(feedback_params) do
      {:ok, feedback} ->
        conn
        |> put_flash(:info, "Feedback created successfully.")
        |> redirect(to: Routes.feedback_path(conn, :show, feedback))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    feedback = Studentcomment.get_feedback!(id)
    render(conn, "show.html", feedback: feedback)
  end

  def edit(conn, %{"id" => id}) do
    feedback = Studentcomment.get_feedback!(id)
    changeset = Studentcomment.change_feedback(feedback)
    render(conn, "edit.html", feedback: feedback, changeset: changeset)
  end

  def update(conn, %{"id" => id, "feedback" => feedback_params}) do
    feedback = Studentcomment.get_feedback!(id)

    case Studentcomment.update_feedback(feedback, feedback_params) do
      {:ok, feedback} ->
        conn
        |> put_flash(:info, "Feedback updated successfully.")
        |> redirect(to: Routes.feedback_path(conn, :show, feedback))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", feedback: feedback, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    feedback = Studentcomment.get_feedback!(id)
    {:ok, _feedback} = Studentcomment.delete_feedback(feedback)

    conn
    |> put_flash(:info, "Feedback deleted successfully.")
    |> redirect(to: Routes.feedback_path(conn, :index))
  end
end

lib/react_workshop_feedback_web/views/feedback_view.ex
defmodule ReactWorkshopFeedbackWeb.FeedbackView do
  use ReactWorkshopFeedbackWeb, :view
end

lib/react_workshop_feedback_web/templates/feedback/edit.html.eex
<h1>Edit Feedback</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.feedback_path(@conn, :update, @feedback)) %>

<span><%= link "Back", to: Routes.feedback_path(@conn, :index) %></span>

lib/react_workshop_feedback_web/templates/feedback/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, ~s(How was the day1 session of,HTML , CSS, Javascript?) %>
  <%= textarea f, :session1_feedback %>
  <%= error_tag f, :session1_feedback %>

  <%= label f, "How was the day2 session, ReactJs?" %>
  <%= textarea f, :session2_feedback %>
  <%= error_tag f, :session2_feedback %>

  <%= label f, ~s(How was the food?) %>
  <%= textarea f, :food_feedback %>
  <%= error_tag f, :food_feedback %>

  <%= label f, ~s(How can we make the session better) %>
  <%= textarea f, :improvement %>
  <%= error_tag f, :improvement %>

  <%= label f, ~s(What topic do you recommend for the next workshop?) %>
  <%= textarea f, :next_session %>
  <%= error_tag f, :next_session %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/react_workshop_feedback_web/templates/feedback/index.html.eex
<h1>Listing Feedbacks</h1>

<table>
  <thead>
    <tr>
      <th>Session1 feedback</th>
      <th>Session2 feedback</th>
      <th>Food feedback</th>
      <th>Improvement</th>
      <th>Next session</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for feedback <- @feedbacks do %>
    <tr>
      <td><%= feedback.session1_feedback %></td>
      <td><%= feedback.session2_feedback %></td>
      <td><%= feedback.food_feedback %></td>
      <td><%= feedback.improvement %></td>
      <td><%= feedback.next_session %></td>

      <td>
        <%= link "Show", to: Routes.feedback_path(@conn, :show, feedback) %>
        <%= link "Edit", to: Routes.feedback_path(@conn, :edit, feedback) %>
        <%= link "Delete", to: Routes.feedback_path(@conn, :delete, feedback), method: :delete, data: [confirm: "Are you sure?"] %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Feedback", to: Routes.feedback_path(@conn, :new) %></span>

lib/react_workshop_feedback_web/templates/feedback/new.html.eex
<h1>New Feedback</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.feedback_path(@conn, :create)) %>

<%# <span><%= link "Back", to: Routes.feedback_path(@conn, :index) %></span>

lib/react_workshop_feedback_web/templates/feedback/show.html.eex
<h1>Show Feedback</h1>

<ul>

  <li>
    <strong>Session1 feedback:</strong>
    <%= @feedback.session1_feedback %>
  </li>

  <li>
    <strong>Session2 feedback:</strong>
    <%= @feedback.session2_feedback %>
  </li>

  <li>
    <strong>Food feedback:</strong>
    <%= @feedback.food_feedback %>
  </li>

  <li>
    <strong>Improvement:</strong>
    <%= @feedback.improvement %>
  </li>

  <li>
    <strong>Next session:</strong>
    <%= @feedback.next_session %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.feedback_path(@conn, :edit, @feedback) %></span>
<%# <span><%= link "Back", to: Routes.feedback_path(@conn, :index) %></span> 
<center>
  <h3>Thank you for coming, We look forward to more learning with you</h3>
  <h3>If you are interested in joining FSFTN then please...</h3>
  <h3><%= link "Please Fill out this form", to: Routes.volunteer_path(@conn, :new) %></h3>
</center>